data_path:
  routing_data_train: 'routing_data/routing_data_train.csv'
  routing_data_val: 'routing_data/routing_data_validate.csv'
  routing_data_test: 'routing_data/routing_data_test.csv'
  llm_data: 'llm_data.json'
  llm_embedding_data: 'llm_embedding_data.pkl'

model_path:
  ini_model_path: ''
  save_model_path: 'personalized/saved_models/personalizedrouter.pt'
  load_model_path: 'personalized/saved_models/personalizedrouter.pt'

hparam:
  embedding_dim: 64
  user_num: 200
  learning_rate: 0.001
  weight_decay: 0.0001
  train_epoch: 60
  llm_family: []
  random_state: 42
